version: 0.2

phases:

  install:
    commands:
      - echo Installing test dependencies...
      - pip install -r requirements.txt

      - echo Building Lambda layer...
      - rm -rf layers/common/python
      - mkdir -p layers/common/python
      - pip install -r requirements.txt -t layers/common/python
      - pip install aws-sam-cli

  pre_build:
    commands:
      - echo Running tests...
      - export PYTHONPATH=$PYTHONPATH:$(pwd)/src
      - export DATABASE_URL=test
      - export USER_POOL_ID=test
      - export CLIENT_ID=test
      - export AWS_REGION=ap-south-1
      - python -m pytest tests -v

  build:
    commands:
      - echo Building SAM application...
      - sam build -t devops/template.yaml

  post_build:
    commands:
      - echo Packaging SAM application...
      - |
        sam package \
          --template-file .aws-sam/build/template.yaml \
          --s3-bucket user-service-artifacts-s3 \
          --output-template-file packaged-template.yaml

artifacts:
  files:
    - packaged-template.yaml