AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

  DatabaseUrl:
    Type: String
    NoEcho: true

Globals:
  Function:
    Timeout: 30
    Runtime: python3.14
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        STAGE: !Ref Stage
        USER_POOL_ID: !Ref UserPool
        CLIENT_ID: !Ref UserPoolClient
        DATABASE_URL: !Ref DatabaseUrl

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${Environment}-users'
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: false
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub '${Environment}-client'
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  ProfileApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub '${Environment}-api'
      StageName: !Ref Stage
      OpenApiVersion: 3.0.1
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn
      Cors:
        AllowMethods: "'GET', 'POST', 'PUT', 'DELETE'"
        AllowHeaders: "'Authorization,Content-Type'"
        AllowOrigin: "'*'"

  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub '${Environment}-common-layer'
      Description: Common dependencies for Lambda functions
      ContentUri: ../layers/common
      CompatibleRuntimes:
        - python3.13

  ProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'message-${Environment}-users-function'
      CodeUri: ../src/services/users
      Handler: user_handler.lambda_handler
      Layers:
        - !Ref CommonLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:SignUp
                - cognito-idp:ConfirmSignUp
                - cognito-idp:InitiateAuth
                - cognito-idp:GetUser
              Resource: !GetAtt UserPool.Arn
      Events:
        CreateUser:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/auth/users
            Method: POST
            Auth:
              Authorizer: NONE
        ConfirmUser:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/auth/confirm
            Method: POST
            Auth:
              Authorizer: NONE
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/auth/login
            Method: POST
            Auth:
              Authorizer: NONE
        GetUser:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/auth/me
            Method: GET
      
  DirectConversationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'message-${Environment}-direct-conversation-function'
      CodeUri: ../src/services/direct_conversation
      Handler: direct_conversation_lambda.lambda_handler
      Layers:
        - !Ref CommonLayer
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        StartDirectConversation:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/direct/conversations
            Method: POST
        GetUserConversations:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/direct/conversations
            Method: GET
        GetConversationById:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/direct/conversations/{dm_id}
            Method: GET

  DirectMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'message-${Environment}-direct-message-function'
      CodeUri: ../src/services/direct_message
      Handler: direct_message_lambda.lambda_handler
      Layers:
        - !Ref CommonLayer
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        SendDirectMessage:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/direct/conversations/{dm_id}/messages
            Method: POST
        GetDirectMessages:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/direct/conversations/{dm_id}/messages
            Method: GET
        GetDirectMessageById:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/direct/conversations/{dm_id}/messages/{message_id}
            Method: GET
        UpdateDirectMessage:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/direct/messages/{message_id}
            Method: PATCH
        DeleteDirectMessage:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/direct/messages/{message_id}
            Method: DELETE

  GroupConversationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'message-${Environment}-group-conversation-function'
      CodeUri: ../src/services/group_conversation
      Handler: group_conversation_lambda.lambda_handler
      Layers:
        - !Ref CommonLayer
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        StartGroupConversation:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/group/conversations
            Method: POST
        GetUserConversations:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/group/conversations
            Method: GET
        GetConversationById:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/group/conversations/{group_id}
            Method: GET
        UpdateGroupConversation:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/group/conversations/{group_id}
            Method: PATCH
        DeleteGroupConversation:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/group/conversations/{group_id}
            Method: DELETE
  GroupMemberFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'message-${Environment}-group-member-function'
      CodeUri: ../src/services/group_members
      Handler: group_member_lambda.lambda_handler
      Layers:
        - !Ref CommonLayer
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        AddGroupMember:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/group/conversations/{group_id}/members
            Method: POST
        GetGroupMembers:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/group/conversations/{group_id}/members
            Method: GET
        UpdateGroupMember:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/group/conversations/{group_id}/members/{user_id}
            Method: PATCH
        RemoveGroupMember:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/group/conversations/{group_id}/members/{user_id}
            Method: DELETE

  GroupMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'message-${Environment}-group-message-function'
      CodeUri: ../src/services/group_message
      Handler: group_message_lambda.lambda_handler
      Layers:
        - !Ref CommonLayer
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        SendGroupMessage:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/group/conversations/{group_id}/messages
            Method: POST
        GetGroupMessages:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/group/conversations/{group_id}/messages
            Method: GET
        UpdateGroupMessage:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/group/conversations/{group_id}/messages/{message_id}
            Method: PATCH
        DeleteGroupMessage:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/group/conversations/{group_id}/messages/{message_id}
            Method: DELETE
        GroupMessageMarkAsRead:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/group/conversations/{group_id}/messages/{message_id}/read
            Method: POST

Outputs:
  ApiUrl:
    Description: "API Gateway URL"
    Value: !Sub "https://${ProfileApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"

  UserPoolId:
    Description: "User Pool ID"
    Value: !Ref UserPool
  UserPoolClientId:
    Description: "User Pool Client ID"
    Value: !Ref UserPoolClient

  ProfileApi:
    Description: "Profile API ID"
    Value: !Ref ProfileApi

  CommonLayer:
    Description: "Common Layer"
    Value: !Ref CommonLayer
  ProfileFunction:
    Description: "Profile Function ARN"
    Value: !GetAtt ProfileFunction.Arn
  DirectConversationFunction:
    Description: "Direct Conversation Function ARN"
    Value: !GetAtt DirectConversationFunction.Arn
  DirectMessageFunction:
    Description: "Direct Message Function ARN"
    Value: !GetAtt DirectMessageFunction.Arn
  GroupConversationFunction:
    Description: "Group Conversation Function ARN"
    Value: !GetAtt GroupConversationFunction.Arn 
  GroupMessageFunction:
    Description: "Group Message Function ARN"
    Value: !GetAtt GroupMessageFunction.Arn
  GroupMemberFunction:
    Description: "Group Member Function ARN"
    Value: !GetAtt GroupMemberFunction.Arn