AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

  DatabaseUrl:
    Type: String
    NoEcho: true

Resources:
  InfraStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates/infra.yaml
      Parameters:
        Environment: !Ref Environment
        Stage: !Ref Stage

  AuthStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates/auth.yaml
      Parameters:
        Environment: !Ref Environment
        Stage: !Ref Stage
        DatabaseUrl: !Ref DatabaseUrl
        UserPoolArn: !GetAtt InfraStack.Outputs.UserPoolArn
        UserPoolId: !GetAtt InfraStack.Outputs.UserPoolId
        UserPoolClientId: !GetAtt InfraStack.Outputs.UserPoolClientId
        ProfileApiId: !GetAtt InfraStack.Outputs.ProfileApiId
        CommonLayerArn: !GetAtt InfraStack.Outputs.CommonLayerArn

  DirectConversationStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates/direct_conversation.yaml
      Parameters:
        Environment: !Ref Environment
        Stage: !Ref Stage
        DatabaseUrl: !Ref DatabaseUrl
        ProfileApiId: !GetAtt InfraStack.Outputs.ProfileApiId
        CommonLayerArn: !GetAtt InfraStack.Outputs.CommonLayerArn

  DirectMessageStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates/direct_message.yaml
      Parameters:
        Environment: !Ref Environment
        Stage: !Ref Stage
        DatabaseUrl: !Ref DatabaseUrl
        ProfileApiId: !GetAtt InfraStack.Outputs.ProfileApiId
        CommonLayerArn: !GetAtt InfraStack.Outputs.CommonLayerArn

  GroupConversationStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates/group_conversation.yaml
      Parameters:
        Environment: !Ref Environment
        Stage: !Ref Stage
        DatabaseUrl: !Ref DatabaseUrl
        ProfileApiId: !GetAtt InfraStack.Outputs.ProfileApiId
        CommonLayerArn: !GetAtt InfraStack.Outputs.CommonLayerArn

  GroupMemberStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates/group_members.yaml
      Parameters:
        Environment: !Ref Environment
        Stage: !Ref Stage
        DatabaseUrl: !Ref DatabaseUrl
        ProfileApiId: !GetAtt InfraStack.Outputs.ProfileApiId
        CommonLayerArn: !GetAtt InfraStack.Outputs.CommonLayerArn

  GroupMessageStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates/group_message.yaml
      Parameters:
        Environment: !Ref Environment
        Stage: !Ref Stage
        DatabaseUrl: !Ref DatabaseUrl
        ProfileApiId: !GetAtt InfraStack.Outputs.ProfileApiId
        CommonLayerArn: !GetAtt InfraStack.Outputs.CommonLayerArn

Outputs:
  ApiUrl:
    Description: "API Gateway URL"
    Value: !GetAtt InfraStack.Outputs.ApiUrl

  UserPoolId:
    Description: "User Pool ID"
    Value: !GetAtt InfraStack.Outputs.UserPoolId
  UserPoolClientId:
    Description: "User Pool Client ID"
    Value: !GetAtt InfraStack.Outputs.UserPoolClientId

  ProfileApi:
    Description: "Profile API ID"
    Value: !GetAtt InfraStack.Outputs.ProfileApiId

  CommonLayer:
    Description: "Common Layer"
    Value: !GetAtt InfraStack.Outputs.CommonLayerArn
  ProfileFunction:
    Description: "Profile Function ARN"
    Value: !GetAtt AuthStack.Outputs.ProfileFunctionArn
  DirectConversationFunction:
    Description: "Direct Conversation Function ARN"
    Value: !GetAtt DirectConversationStack.Outputs.DirectConversationFunctionArn
  DirectMessageFunction:
    Description: "Direct Message Function ARN"
    Value: !GetAtt DirectMessageStack.Outputs.DirectMessageFunctionArn
  GroupConversationFunction:
    Description: "Group Conversation Function ARN"
    Value: !GetAtt GroupConversationStack.Outputs.GroupConversationFunctionArn 
  GroupMessageFunction:
    Description: "Group Message Function ARN"
    Value: !GetAtt GroupMessageStack.Outputs.GroupMessageFunctionArn
  GroupMemberFunction:
    Description: "Group Member Function ARN"
    Value: !GetAtt GroupMemberStack.Outputs.GroupMemberFunctionArn