AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
	Environment:
		Type: String
	Stage:
		Type: String
	DatabaseUrl:
		Type: String
	UserPoolArn:
		Type: String
	UserPoolId:
		Type: String
	UserPoolClientId:
		Type: String
	ProfileApiId:
		Type: String
	CommonLayerArn:
		Type: String

Globals:
  Function:
    Timeout: 30
    Runtime: python3.14
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        STAGE: !Ref Stage
        USER_POOL_ID: !Ref UserPool
        CLIENT_ID: !Ref UserPoolClient
        DATABASE_URL: !Ref DatabaseUrl

Resources:
	ProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'message-${Environment}-users-function'
      CodeUri: ../src/services/users
      Handler: user_handler.lambda_handler
      Layers:
        - !Ref CommonLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:SignUp
                - cognito-idp:ConfirmSignUp
                - cognito-idp:InitiateAuth
                - cognito-idp:GetUser
              Resource: !GetAtt UserPool.Arn
      Events:
        CreateUser:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/auth/users
            Method: POST
            Auth:
              Authorizer: NONE
        ConfirmUser:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/auth/confirm
            Method: POST
            Auth:
              Authorizer: NONE
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/auth/login
            Method: POST
            Auth:
              Authorizer: NONE
        GetUser:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/auth/me
            Method: GET

Outputs:
	ProfileFunctionArn:
		Value: !GetAtt ProfileFunction.Arn
