AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
	Environment:
		Type: String
	Stage:
		Type: String
	DatabaseUrl:
		Type: String
	ProfileApiId:
		Type: String
	CommonLayerArn:
		Type: String

Globals:
	Function:
		Timeout: 30
		Runtime: python3.14
		Environment:
			Variables:
				ENVIRONMENT: !Ref Environment
				STAGE: !Ref Stage
				DATABASE_URL: !Ref DatabaseUrl

Resources:
	DirectMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'message-${Environment}-direct-message-function'
      CodeUri: ../src/services/direct_message
      Handler: direct_message_lambda.lambda_handler
      Layers:
        - !Ref CommonLayer
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        SendDirectMessage:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/direct/conversations/{dm_id}/messages
            Method: POST
        GetDirectMessages:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/direct/conversations/{dm_id}/messages
            Method: GET
        GetDirectMessageById:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/direct/conversations/{dm_id}/messages/{message_id}
            Method: GET
        UpdateDirectMessage:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/direct/messages/{message_id}
            Method: PATCH
        DeleteDirectMessage:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/direct/messages/{message_id}
            Method: DELETE

Outputs:
	DirectMessageFunctionArn:
		Value: !GetAtt DirectMessageFunction.Arn
