AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
	Environment:
		Type: String
	Stage:
		Type: String
	DatabaseUrl:
		Type: String
	ProfileApiId:
		Type: String
	CommonLayerArn:
		Type: String

Globals:
	Function:
		Timeout: 30
		Runtime: python3.14
		Environment:
			Variables:
				ENVIRONMENT: !Ref Environment
				STAGE: !Ref Stage
				DATABASE_URL: !Ref DatabaseUrl

Resources:
	GroupMemberFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'message-${Environment}-group-member-function'
      CodeUri: ../src/services/group_members
      Handler: group_member_lambda.lambda_handler
      Layers:
        - !Ref CommonLayer
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        AddGroupMember:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/group/conversations/{group_id}/members
            Method: POST
        GetGroupMembers:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/group/conversations/{group_id}/members
            Method: GET
        UpdateGroupMember:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/group/conversations/{group_id}/members/{user_id}
            Method: PATCH
        RemoveGroupMember:
          Type: Api
          Properties:
            RestApiId: !Ref ProfileApi
            Path: /api/v1/group/conversations/{group_id}/members/{user_id}
            Method: DELETE

Outputs:
	GroupMemberFunctionArn:
		Value: !GetAtt GroupMemberFunction.Arn
